name: C Build & Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt update && sudo apt install build-essential -y

      - name: Compile Grade‑Analyzer Indonesia Ver.
        run: gcc Grade-Analyzer-id.c -o grade-analyzer-id

      - name: Run program (with sample input)
        run: |
          echo "Sample Input" | ./grade-analyzer-id
